### ISSUE TITLE
Some classes missing ?

### ISSUE THREAD

**Issue by stonny71** [atoms19/ILUS.CSS#5]
It seems you are missing some classes.
Padding, margin and card class.

**Comment by atoms19** [comment]
card class is already there, I'll add padding and margin in the next update

**Comment by stonny71** [comment]
Ok.
That will be great.
could you also add responsive classes?
I suggest inco-operating "dead-simple" framework to Ilus, that would be
great.

**Comment by atoms19** [comment]
added a lot of classes in last update
